name: Label Issues
on:
    issues:
        types:
            - reopened
            - opened

jobs:
    label_issues:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: Set Labels
              uses: actions/github-script@v6
              with:
                  script: |
                      const templates = {
                        'Bug Report': ['bug', 'needs-triage'],
                        'Feature Request': ['enhancement', 'needs-review'],
                      };

                      const issueType = context.payload.issue.body.match(/## (\w+)/)[1];

                      if (issueType in templates) {
                        const labelsToAdd = templates[issueType];
                        
                        const existingLabels = await github.rest.issues.listLabelsOnIssue({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo
                        });

                        const existingLabelNames = existingLabels.data.map(label => label.name);
                        const labelsToAddFiltered = labelsToAdd.filter(label => !existingLabelNames.includes(label));

                        if (labelsToAddFiltered.length > 0) {
                          await github.rest.issues.addLabels({
                            issue_number: context.issue.number,
                            owner: context.repo.owner,
                            repo: context.repo.repo,
                            labels: labelsToAddFiltered
                          });
                        }
                      }
